### ISSUE TITLE
Abstract Round

### ISSUE THREAD

**Issue by jetjoshi** [atharvapatil22/PokerAI#13]
Round is currently within the poker class. We need to remove the functionality of round from poker to make the code easier to read and modularize the code. 

Refactoring Round:
Attributes:
- Players Array
- Board object
- Phase (a number)
- Deck
- ButtonPlayerIndex

Functions
- runRound() -> returns players remaining
- init(players, deck, minbet)
- call(activePlayerIndex)
- fold(activePlayerIndex)
- raise(activePlayerIndex)
- check(activePlayerIndex)
- allIn(activePlayerIndex)
- minBet(activePlayerIndex)
- lowBet(activePlayerIndex)
- mediumBet(activePlayerIndex)
- highBet(activePlayerIndex)
- scoreHand(activePlayerIndex)

**Comment by brettyukino9** [comment]
https://github.com/atharvapatil22/PokerAI/pull/31
