### ISSUE TITLE
Create Minimax Agent Structure

### ISSUE THREAD

**Issue by TiptonG** [atharvapatil22/PokerAI#58]

**Comment by atharvapatil22** [comment]
**_Implementation Version 1_**
Currently we will implement an algorithm that runs minimax for each phase. This way we can avoid calculating the permutations and combinations for all the cards that can show up in consecutive phases. 
We will later expand our algorithm consider all phases at once.

For utility we will consider hand strength and Amount in pot. More details on the utility issue.
