### ISSUE TITLE
Utility Score MegaIssue

### ISSUE THREAD

**Issue by TiptonG** [atharvapatil22/PokerAI#61]
Comment relevant updates and progress

**Comment by TiptonG** [comment]
Start by accounting for only initial two cards in hand and pot size in utility function, later we can add stuff like n simulations to get community cards

**Comment by jetjoshi** [comment]
We will run minimax on each phase. On the first phase, we will have the utility function a 2 hand scoring denoted by the following table: https://homes.luddy.indiana.edu/kapadia/nofoldem/2_wins.stats and the pot size at the end. For the rest of the phases, we will have 5, 6, and 7 card hand score. The utility value will be a constant value which will be determined by how high the hand score is and how high the pot size. The hand score and pot size are denoted by the following:
High: 100 - 75% (for pot size total money compared to current amount agent has)
Med: 75 - 50%
Low: 50-0%

Here is the utility (hand score, pot size):
high high: 90
high mid: 80
high low: 70
mid high: 60
mid mid: 70
mid low: 60
low high: 30
low mid: 40
low low: 50
