### ISSUE TITLE
Tiebreaker code can be removed

### ISSUE THREAD

**Issue by brettyukino9** [atharvapatil22/PokerAI#70]
If two hands have the exact same score the pot is split. We currently have it so that the players hand is used as a tiebreaker, and this can be removed.

Test by making the game have the cards 2, 2, 2, 3, 7 He, 8 He, 9 He, 10 He, Q He
if working correctly the pot should be split, not have 2 win.

**Comment by TiptonG** [comment]
fixed in #76
