### ISSUE TITLE
MCTS method locations

### ISSUE THREAD

**Issue by TiptonG** [atharvapatil22/PokerAI#79]
Low priority issue

I feel like some of the methods in MonteCarloAgent.MCTree should just be in MonteCarloAgent instead. Especially all of the static ones in there, and even some of the non-static ones could be made static and moved out to MonteCarloAgent. I feel like I overloaded the MCTree with functionality unintentionally. It gets weird/annoying having to type `MonteCarloAgent.MCTree.<method>` for every method I want to use.
Moving things out won't be difficult... but deciding what and what not to move might be tedious.

This should most definitely wait until it has been tested, that way untested code isn't undergoing massive change before it can be confirmed that it works (and before initial identity is lost). Plus, moving the methods should not impact functionality in the slightest, so this is more of a cosmetic/code readability change.

**Comment by brettyukino9** [comment]
Not getting done
